name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t your-image:latest .
          docker images

      - name: Push Docker image
        run: |
          echo ${{ 'secrets.laithkumar11' }} | docker login --username ${{ 'secrets.laithdocker123' }} --password-stdin
          docker push your-image:latest
